title: BnF640
description: ""
baseurl: "/bnf640" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
