title: IIIF Annotation Demo
description: ""
baseurl: "/annotate" # the subpath of your site, e.g. /blog
url: "http://marii.info" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty

github_username: mnyrop
social_username: mariinyrop

theme: jekyll-swiss

exclude: [Rakefile, Gemfile*]

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
